### ISSUE TITLE
Module does not scale past 100 clients 

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#11]
Dev Estimate: 0
Test Estimate: 0

Socket.IO writes to the store occasionally to update it with the current status of the connected clients. This module dutifully sends those messages to the Service Bus, where they go into the subscriptions for each node instance.

From what I see on my test machine, Socket.IO sends 2 messages to the store for each connected client, every 20 seconds (or so). So, 100 clients, distributed across any number of nodes (even one) results in the subscriptions getting filled with 10 messages per seconds, in the quiescent state. 

The bad news is, that this module can _at maximum_ only pull 10 messages per second from the subscription. So, once you get 100 clients, even with nobody writing anything in the chat window, the subscription will backlog, and messages from peer nodes will be delayed by ever increasing amounts.

**Comment by christav** [comment]
I set estimates at zero because the work to address this is tracked under separate bugs. Keeping this bug around to track the overall effort.

**Comment by jcookems** [comment]
Looks good.
