### ISSUE TITLE
Implement multiple simultaneous receives

### ISSUE THREAD

**Issue by christav** [azure-contrib/socket.io-servicebus#15]
Dev Estimate: 8
Test Estimate: 8

As part of improving perf, have the service bus interface do 8 multiple simultaneous receive calls. This should improve latency significantly.

Will require logic to detect out-of-order reception of messages.

**Comment by jcookems** [comment]
Why 8? What are the pros/cons for higher and lower?

**Comment by christav** [comment]
8 is recommendation of ServiceBus team - it's the minimum number of head-end machines for service bus in each data center; some have more.

**Comment by christav** [comment]
Upon experimentation, 4 seems to be the best number. Need to build test harness to actually measure throughput in a meaningful way.

**Comment by jcookems** [comment]
I've started testing this, and it looks good.

I assume that the 8 storypoints for test includes the stress test harness that @christav is working on. The remainder if my work for testing this work item is assisting when needed with that work.

**Comment by glennblock** [comment]
In terms of numbers, I think it was 8 receivers across 2 vms.

**Comment by jcookems** [comment]
Looks good.
