### ISSUE TITLE
Build "spew/slurp" sample to test throughput

### ISSUE THREAD

**Issue by christav** [azure-contrib/socket.io-servicebus#23]
Dev Estimate: 5
Test Estimate: 3

We need a sample we can run that just tries to send & receive messages as quickly as possible over an arbitrary # of servers and clients, so we can more reliably measure our throughput / scalability.

**Comment by jcookems** [comment]
I've taken an initial look at the app. Some comments:
1. In the current state, the sample does not exercise the `socket.io-servicebus` module, so I don't think it is appropriate to be in the `examples` folder as-is. Consider adding in use of this module, or move into a different location (like "tools"?).
2. The "send" part of the app does not work with IE, but does work in Chrome. 
3. I don't know what to validate for this sample. It appears to correctly process its inputs, but the next step is fuzzy for me (kind of getting back to the point of #1). I think this is helpful for the app developer, but not so useful for the consumer.
