### ISSUE TITLE
Add retry logic on SB send

### ISSUE THREAD

**Issue by christav** [azure-contrib/socket.io-servicebus#33]
Dev Estimate: 2
Test Estimate: 3

If a send to service bus fails, we should retry rather than just logging and failing.

**Comment by christav** [comment]
@jcookems I added a guess at a test estimate, not sure how to force a failure from Service Bus to really test this. The retry logic itself is from the SDK and presumably is already sufficiently tested.

**Comment by jcookems** [comment]
Repro:
1. Start Fiddler.
2. Set up one Chat server, with `HTTP_PROXY=http://127.0.0.1:8888`
3. Set up another chat server, without the proxy.
4. Setup two clients, one for each server. Get them set up and send a few messages to prime the pump.
5. In Fiddler, set to break before requests. 
6. In the client for the first server, send a message.
7. In Fiddler, corrupt the auth token for a "dispatch" message from the module by adding extra junk characters.
8. Set Fiddler to no longer break, and resume all messages.
9. See that the dispatch message returns a `401 Unauthorized`

**EXPECT**: That message gets resent, and eventually shows up in the other client.,

**ACTUAL**: Message never arrives at the other client.

**Comment by christav** [comment]
400 errors are "client sent a malformed request". As such, they're explicitly not retried; the assumption there is if the message is invalid, retrying it will just result in another 400-series error. Is there a way to get fiddler to send back a 500 (server-side failure) instead?
