### ISSUE TITLE
Add license to timingtest files

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#40]
Some packages, like `bootstrap` are external, and could benefit from a LICENSE file like in the chat app.

Others, like `underscore`, should probably use the non-minified version so as to retain the original license. For this test app, initial load time is unimportant.

As for code that is missing any license at all, under `examples\timingtest`:
- `public\stylesheets\style.css`
- `views\*.jade`
- `package.json`

Dev Estimate: 0.5
Test Estimate: 0

**Comment by christav** [comment]
The files you're referencing are ours, created by me. Shouldn't the existing license file at the root of the project cover them?

As far as bootstrap and underscore go, they have copyright comments at the top of the files (in the unminified vesions, anyway). Is that sufficient for these files, or do we need an explicit separate license file for them?

**Comment by christav** [comment]
Now pulling underscore and bootstrap from cdn. As we're not distributing them, no need for licensing files.

**Comment by glennblock** [comment]
Thanks for researching the cdn option Chris.
