### ISSUE TITLE
Poor error experience when no subscription is created

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#5]
Just dumbly trying out the chat sample, after setting the appropriate environment variables, but not configuring my SB subscription, I get this

```
Waiting for service bus message from subscription client1
Received message from sb, err = Error, message = undefined
Waiting for service bus message from subscription client1
Received message from sb, err = Error, message = undefined
Waiting for service bus message from subscription client1
^C
```

Good error handling explains (a) what went wrong, and (b) suggests how to fix it.

We can expect that users will not properly set up their topic or subscriptions, so the module should do some input verifications on startup:
1. Ask the SB instance if the topic exists. If not, throw an error saying something like "the specified topic does not exist in this SB instance. Vreify that you have the correct SB instance and that the topic is created."
2. Ask the SB instance if the subscription exists for that topic. If now, thow saying "sub does not exist for topic 'Topic' in the SB insance. Double check"

**Comment by christav** [comment]
We now autocreate subscriptions, experience is clean.
