### ISSUE TITLE
No messages is not an error condition

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#6]
After getting my topic and subscription set up, I see this output:

```
Waiting for service bus message from subscription client1
Received message from sb, err = No messages to receive, message = undefined
Waiting for service bus message from subscription client1
Received message from sb, err = No messages to receive, message = undefined
...

It took me a while to realize that it was working (I think) correctly. Errors should be reserved for exceptional events. If there are no messages, I'd expect the app to output something less alarming, like this:
```

Waiting for service bus message from subscription client1
No messages to receive
Waiting for service bus message from subscription client1
No messages to receive
...

**Comment by christav** [comment]
The logging is simply printing the contents of the "error" parameter received by the callback. Unfortunately the service bus API returns an error with that string when there's no message.

**Comment by markcowl** [comment]
over time, do we want to detect this particular error and only include it in verbose logging?

**Comment by christav** [comment]
These messages have been removed from the codebase, closing. Will add verbose logging for the poll/no message case under the logging work.
