### ISSUE TITLE
Investigate intermittent failure to communicate with Service Bus bi-directionally socket.io instances

### ISSUE THREAD

**Issue by glennblock** [azure-contrib/socket.io-servicebus#67]
Dev Estimate: 20
Test Estimate: 0

**Comment by christav** [comment]
Service bus is having really poor perf at the moment; working with SB team to see if this is causing our issues.

**Comment by christav** [comment]
Some investigation results:
- Still very slow perf on receives - after a while receives just stop returning.
- Servicebus is deleting subscriptions out from under me, while they have data in them and we're actively polling
- At least once I saw a 500 series error when trying to set up the topic. Retry filter should have handled this, but it didn't.

**Comment by christav** [comment]
Looks like the service bus issues have cleared up. Closing this for now, will reopen if the server side issues occur again.
