### ISSUE TITLE
Consider using non-deprecated UUID methods

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#7]
To generate a new node id, the `sbstore` uses this code:

``` js
  this.nodeId = (options && options.nodeId) || uuid();
```

But the docs at https://github.com/broofa/node-uuid say

> Support for the following v1.2 APIs is available in v1.3, but is deprecated and will be removed in the next major version.
> `uuid([format [, buffer [, offset]]])`

**Comment by richorama** [comment]
Hat seems to be the most popular alternative?
https://npmjs.org/package/hat

**Comment by jcookems** [comment]
Looks good.
