### ISSUE TITLE
Updating for Socket.IO 1.0

### ISSUE THREAD

**Issue by shijuvar** [azure-contrib/socket.io-servicebus#73]
Socket.IO 1.0 has released - http://socket.io/blog/introducing-socket-io-1-0/. Has any plan for update the library for working with Socket.IO 1.0.?

**Comment by ghost** [comment]
We are egerly waiting for this thing to work. We are getting the error (screenshot attached)

Please do update some work around for the same in msahoo@newclassrooms.org

![image](https://cloud.githubusercontent.com/assets/6048590/4267741/f5c81856-3ca1-11e4-9c09-013c23bdaaab.jpg)

**Comment by glennblock** [comment]
Closing as Duplicate of #75
