### ISSUE TITLE
dead project?

### ISSUE THREAD

**Issue by dotnetwise** [azure-contrib/socket.io-servicebus#74]
It seems dead to me!

**Comment by agonbina** [comment]
Yeah, just when you get excited about an Azure service for NodeJS, you find out it's dead or barely supported ...

**Comment by glennblock** [comment]
sigh. 

I've had talks with some folks who are interested in taking this over.

Hey @guangyang @shanselman any chance we can transfer this to the community if there is not going to be any further investment?

**Comment by rickggaribay** [comment]
I'd be interested in contributing.

**Comment by glennblock** [comment]
Awesome!

**Comment by glennblock** [comment]
Who else wants to help take this over?

**Comment by glennblock** [comment]
That is assuming it was transferred to the community.....

**Comment by christav** [comment]
@glennblock Yeah, you're jumping the gun a little bit here. I'm surprised, you never do that. :-)

**Comment by glennblock** [comment]
The two messages were back to back ;-)

**Comment by glennblock** [comment]
And now for something different.

This is live now: https://github.com/azure-contrib/socket.io-servicebus

**Comment by glennblock** [comment]
@dotnetwise let's bring it back to life!

**Comment by glennblock** [comment]
Uh @guangyang @shanselman it's been 6 months. Should I expect the full transfer to azure-contrib ever to happen?

We also need the npm package rights so we could publish unless we need to publish a new one like "socket.io-servicebus-stillalive" ;-)

**Comment by glennblock** [comment]
Not anymore. This just transferred over to azure-contrib. We now have full ownership to take this forward!

Who is ready?
