### ISSUE TITLE
Unexpected messages should not crash app

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#8]
I tried writing to the topic from another app, thinking about how to stress it some. When running the chat app:

EXPECT:

The log will show an error, like "Badly formed message, ignoring and carrying on".

ACTUAL:

The app dies a horrible death:

```
Waiting for service bus message from subscription client1
Received message from sb, err = null, message = { body: 'text/plain',
  brokerProperties:
   { DeliveryCount: 1,
     MessageId: 'ae3c39407f1e47c7b00a502a7f26426f',
     SequenceNumber: 673,
     State: 'Active',
     TimeToLive: 1209600 },
  contentType: 'text/plain' }

undefined:1

^
SyntaxError: Unexpected token e
    at Object.parse (native)
    at Formatter.unpack (C:\dd\git\jcooke\socket.io-servicebus\examples\chat\node_modules\socket.io-servicebus\lib\formatter.js:39:16)
...
```

I thought a bit about how this could happen in normal usage,like
-  network hiccup flipping a bit (but that can't really happen over SSL, whole message would be invalid)
- malicious user trying to attach the SB endpoint (but that would involve knowing the owner credentials to send those messages, in which case you are in big trouble already)
- message contains characters that cannot be roundtripped (which would be a bug in the underlying JSON, which seems unlikely)

So, it seems unlikely to be a "real" issue, but if it ever crops up, it will _kill_ all clients, which is terrible, so it seems like we should try to be secure by default.

**Comment by glennblock** [comment]
Is this closed?

**Comment by glennblock** [comment]
@christav is this closed?

**Comment by christav** [comment]
@glennblock I think it is, but it was never verified by test.

**Comment by glennblock** [comment]
@christav you move it in the sprint?

-----Original Message-----
