### ISSUE TITLE
Subscription messages drain slowly

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#9]
Dev Estimate: 0
Test Estimate: 5

When running the chat app on my desktop computer, the subscription drains messages at a rate of 400 "messages" per minute. The actual number of end-user messages processed per minute is going to be even lower, because some fraction (75%?) of those messages are used by Socket.IO store for book-keeping.

That means that the number of chat messages processed per minute is going to be about 100, which sounds quite bad.

I believe that the throughput could be increased by asking the subscription for _all_ available messages in a batch. But that option might only be available for Storage Queues :-(

**Comment by jcookems** [comment]
Or perhaps the module should pre-batch the messages, and send chunkier, composite messages.

**Comment by christav** [comment]
I believe this was addressed by batching the sent messages.

**Comment by jcookems** [comment]
It now behaves _much_ better for huge storms of chat messages. I find (on my laptop) that 2000 chat messages get sent to all clients in about 20 seconds or so. (It is hard to tell exactly, but the SB subscriptions get emptied in under 30 seconds).

**Comment by glennblock** [comment]
Excellent news!

**Comment by jcookems** [comment]
Looks good.
